# -*- coding: utf-8 -*-
"""Disaster Tracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VnSczM79bgZY2BIuHmN2epTJSSNHkmge
"""

import json
from datetime import datetime

# 🌟 THE OFFLINE FIX: We build a simulated live JSON telemetry stream right into Python.
# This mimics the exact format sent out by real government disaster networks.
mock_live_feed = """
{
    "status": "Success",
    "region": "Georgia, USA",
    "timestamp": "2026-06-18T14:20:00",
    "features": [
        {
            "event_id": "GA-001",
            "type": "Severe Weather Anomaly",
            "hazard": "Flash Flood Emergency",
            "severity_index": 8.4,
            "affected_zones": "Fulton County, DeKalb County, Cobb County",
            "details": "Rapid rainfall exceeding 3 inches per hour. Damaging flash floods actively reported over low-lying highway matrices."
        },
        {
            "event_id": "GA-002",
            "type": "Geological Shift Anomaly",
            "hazard": "Minor Seismic Tremor",
            "severity_index": 2.1,
            "affected_zones": "Northwest Georgia Border Region",
            "details": "Low-level micro-earthquake registered by deep geological telemetry arrays. No structural impacts reported."
        },
        {
            "event_id": "GA-003",
            "type": "Atmospheric Danger Anomaly",
            "hazard": "Severe Thunderstorm & High Velocity Winds",
            "severity_index": 7.9,
            "affected_zones": "Savannah Coastline, Chatham County",
            "details": "Radar arrays indicating severe wind velocities tracking over 60 mph with extreme cloud-to-ground lightning clusters."
        }
    ]
}
"""

print("📡 Initializing Offline Public Safety Tracker System Baseline...")
print("📦 Safely unpacking simulated live regional data streams...")

# Unpack the simulated data stream safely without needing any network hardware
data = json.loads(mock_live_feed)
events = data.get('features', [])

print(f"✅ Success! Unpacked {len(events)} live localized hazard logs.")
print("🔍 Analyzing metric thresholds for critical emergency alerts...")
print("-" * 75)

alert_count = 0
for event in events:
    event_type = event.get('type')
    hazard = event.get('hazard')
    severity = event.get('severity_index')
    zones = event.get('affected_zones')
    details = event.get('details')

    # 🧠 Logic Processing Layer: Track index safety boundaries
    # We flag any hazard with a severity index higher than 5.0 as a critical threat
    if severity >= 5.0:
        alert_count += 1

        print(f"🚨 CRITICAL REGIONAL EMERGENCY FLAG #{alert_count}")
        print(f"   🔹 Anomaly Category: {event_type}")
        print(f"   🔹 Specific Hazard:   {hazard}")
        print(f"   🔹 Threat Intensity:  {severity} / 10.0 Priority Index")
        print(f"   🔹 Affected Sectors:  {zones}")
        print(f"   📝 Incident Log:      {details}")
        print("-" * 75)

if alert_count == 0:
    print("✅ Baseline Stable: All parameters falling within standard index safety boundaries.")